# Generated by Django 4.0.4 on 2022-06-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.location')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.profilepic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
