# Generated by Django 4.0.4 on 2022-06-22 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='profile_pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_api.profilepic'),
            preserve_default=False,
        ),
    ]
