# Generated by Django 4.0.5 on 2022-06-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_location_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
