# Generated by Django 4.0.4 on 2022-06-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_location_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic_id',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profilelocation',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profilelocation',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
