# Generated by Django 4.0.4 on 2022-06-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_rename_profile_pic_id_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='discovered_by',
            field=models.ManyToManyField(related_name='locations', to='app_api.profile'),
        ),
    ]
