# Generated by Django 4.0.4 on 2022-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_rename_img_location_character_art_location_map_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
