# Generated by Django 4.0.4 on 2022-06-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_location_x_location_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='map_icon',
        ),
    ]
